export const SET_PRODUCTS_LIST = "SET_PRODUCTS_LIST";
export const SET_NUTRIENTS_CONFIGURATION = "SET_NUTRIENTS_CONFIGURATION";
export const ADD_PRODUCT_TO_BASKET = "ADD_PRODUCT_TO_BASKET";
export const REMOVE_PRODUCT_FROM_BASKET = "REMOVE_PRODUCT_FROM_BASKET";
